# Cấu hình toàn cục chung cho tất cả các tiến trình thu thập (scrape)
global:
  scrape_interval: 15s      # Tần suất thu thập metric từ các target (mặc định 1 phút, bản cài mẫu thường đặt 15s)
  evaluation_interval: 15s  # Tần suất đánh giá các quy tắc cảnh báo (alerting/recording rules)
  # scrape_timeout: 10s   # Thời gian chờ tối đa cho một lần scrape (mặc định 10s)

# Cấu hình Alertmanager để gửi cảnh báo
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Tải các tệp quy tắc (rules) định kỳ
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Cấu hình danh sách các target cần thu thập metric
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'mern-todo-app'
    static_configs:
      - targets: ['157.245.61.179:9100']
